### ISSUE TITLE
Collect reference literature on the review of literature using network analysis

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ai_edi_space#12]
I have created a wiki page to collect information about the use of social network analysis in the review of literature: https://github.com/CUPUM/ai_edi_space/wiki/Reviewing-literature-with-social-network-analysis

**Comment by hugobb** [comment]
Maybe this website could be of interest to you for the literature review:  https://www.connectedpapers.com
It finds similar paper based on a paper's title or link.

**Comment by sjinko** [comment]
Transferred to : https://github.com/CUPUM/GAN4creativity/issues/2
